[package]
name = "aurion-projection"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
tracing = { workspace = true }
aurion-criptografi = { path = "../aurion-criptografi", version = "0.1.0"}
aurion-core = { path = "../aurion-core", version = "0.1.0"}
aurion-ledger = { path = "../aurion-ledger", version = "0.1.0"}
aurion-execution = { path = "../aurion-execution", version = "0.1.0"}

blake3 = "1.5"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.10"

[lints]
workspace = true
